name: Terraform Workflow deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Public Repository
      - name: Checkout Public Repo
        uses: actions/checkout@v3

      # Step 2: Configure Git Authentication for Private Repo
      - name: Authenticate to GitHub
        run: |
          git config --global url."https://$GIT_TOKEN:@github.com/".insteadOf "https://github.com/"
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate Terraform
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Plan Terraform Changes
      - name: Terraform Plan
        run: terraform plan

      # Step 7: Apply Terraform Changes (Optional)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}